list와 array 차이

# 요소 차이
- list : 숫자형, 문자열 등 모든 자료 타입을 가질 수 있음 (여러 자료형 허용)
- array : 숫자형과 문자열이 혼합되면 모두 문자열로 변환 (한 가지 자료형만 허용)

In [1]:
import numpy as np

In [2]:
lt = [1, 3, 'a', 'b']
ar = np.array([1, 3, 'a', 'b'])

In [3]:
lt

[1, 3, 'a', 'b']

In [4]:
ar

array(['1', '3', 'a', 'b'], dtype='<U11')

# 2차원 이상일 경우, 원소 개수
- list : 요소의 개수가 달라도 됨
- array : 요소의 개수가 모두 같아야 함

In [5]:
lt = [[1], [3, 5], [7, 9, 10]]
ar = np.array([[1], [3, 5], [7, 9, 10]]) #Error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [6]:
ar = np.array([[1, 3], [3, 5], [7, 9]]) 

In [7]:
ar

array([[1, 3],
       [3, 5],
       [7, 9]])

# 연산
- list : 리스트 간 + 연산은 concatenate(이어줌) 수행 (-, *, / 연산 불가능)
- array : +, -, *, / 연산 모두 가능

In [8]:
lt_one = [1, 3, 5]
lt_two = [2, 4, 6]

# 덧셈
lt_one + lt_two

[1, 3, 5, 2, 4, 6]

In [9]:
# 뺄셈
lt_one - lt_two

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [10]:
# 곱셈
lt_one * 3

[1, 3, 5, 1, 3, 5, 1, 3, 5]

In [2]:
ar_one = np.array([1, 3, 5])
ar_two = np.array([2, 4, 6])

ar_one + ar_two

array([ 3,  7, 11])

In [3]:
ar_one - ar_two

array([-1, -1, -1])

In [4]:
ar_one * ar_two

array([ 2, 12, 30])

In [5]:
ar_one / ar_two

array([0.5       , 0.75      , 0.83333333])

In [6]:
ar_one * 2

array([ 2,  6, 10])

# 연산 속도
- time.time()
    - 1970년 1월 1일 0시 0분 0초 이후 경과한 시간을 초단위로 반환
    - 정수부는 초단위이고, 소수부는 마이크로(micro) 초단위
    - 마이크로초(micro-second) : 백만 분의 1초

In [12]:
import time

# 리스트 연산 속도
lt = list(range(10**8))

start = time.time()

for i in lt:
    lt[i] *= 2
    
end = time.time()

print(end - start)

9.37250018119812


In [11]:
even = list(range(5))
for e in even:
    even[e] *= 2
even

[0, 2, 4, 6, 8]

In [13]:
# array 연산 속도
ar = np.array(range(10**8))

start = time.time()
ar = ar * 2
end = time.time()

print(end - start)

0.10902285575866699
