In [1]:
import numpy as np

- numpy 
    - Numerical Python
    - 파이썬의 고성능 과학 계산용 패키지
    - Matrix와 Vector와 같은 Array 연산
    - list에 비해 연산 속도 빠르고, 메모리 효율적 사용
    - 반복문 없이 배열 연산 가능
    - 선형대수와 관련된 다양한 기능을 제공
    - C, C++, 포트란 등의 언어 통합 가능

# 차원에 따른 이름
차원 | 이름 | 예제
- | - | -
0 | scalar | 7
1 | vector | [10, 20]
2 | matrix | [[10, 20], [30, 40]]
3 | 3-tensor | [[[1, 3, 5], [7, 9, 11]], [[2, 4, 6], [8, 10 ,12]]]
n | n-tensor |

## 스칼라 (scalar)
- 상수

In [2]:
np.isscalar(3)

True

In [3]:
np.isscalar(4.2)

True

In [4]:
np.isscalar('hi')

True

In [5]:
np.isscalar(True)

True

In [6]:
np.isscalar([4])

False

In [7]:
np.isscalar(np.array([3, 4]))

False

## 벡터 (vector)
- 크기와 방향을 갖는 물리량
- 공간에서 갖는 하나의 점
- 1차원 배열
- 선
- axis0

In [13]:
ar = np.arange(5)
print(ar)
print(type(ar))
print('ar size >>', ar.size) # 전체 요소의 개수
print('ar len >>', len(ar))  # 해당 축의 요소 개수
print('ar shape >>', ar.shape)  # 크기(길이)가 5인 1차원 배열(벡터)
print('ar dtype >>', ar.dtype)  # 32bit -> 4byte
print('ar nbytes >>', ar.nbytes)  # 메모리 크기 : 4byte * 5개 = 20btye

[0 1 2 3 4]
<class 'numpy.ndarray'>
ar size >> 5
ar len >> 5
ar shape >> (5,)
ar dtype >> int32
ar nbtypes >> 20


## 매트릭스 (matrix)
- 행과 열 : 행렬
- 2차원 배열 : 1차원 배열 여러 개
- 여러 개의 벡터 (벡터를 원소로 갖음)
- 면
- axis0, axis1

In [21]:
ar2 = np.array([ar, ar])
print(ar2)
print('ar2 size >>', ar2.size) # 전체 요소 개수 : 10
print('ar2 len >>', len(ar2)) # 행 길이
print('ar2[0] len >>', len(ar2[0])) # 열 길이
print('ar2 shape >>', ar2.shape) # 크기가 2x5인 2차원 배열(matrix)
print('ar2 dtype >>', ar2.dtype) # 32bit -> 4byte
print('ar2 nbytes >>', ar2.nbytes) # 메모리 크기 : 4byte * 10개 = 40byte

[[0 1 2 3 4]
 [0 1 2 3 4]]
ar2 size >> 10
ar2 len >> 2
ar2[0] len >> 5
ar2 shape >> (2, 5)
ar2 dtype >> int32
ar2 nbytes >> 40


## 텐서 (tensor)
- 행, 열, 깊이/높이/차원
- 3차원 배열 : 2차원 배열 여러 개
- 입체
- axis0, axis1, axis2

In [25]:
ar3 = np.array([ar2, ar2, ar2])
print(ar3)
print('ar3 size >>', ar3.size)
print('ar3 len >>', len(ar3))
print('ar3[0] len >>', len(ar3[0]))
print('ar3 shape >>', ar3.shape)
print('ar3 dtype >>', ar3.dtype)
print('ar3 nbytes >>', ar3.nbytes) # 4byte * 30개 = 120byte

[[[0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]]]
ar3 size >> 30
ar3 len >> 3
ar3[0] len >> 2
ar3 shape >> (3, 2, 5)
ar3 dtype >> int32
ar3 nbytes >> 120


# numpy type 
- int : 정수
- uint : 부호없는 정수 (음수가 없음)
- float : 실수
- comlpex : 복소수 (실수, 허수)
- bool : 논리

In [26]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [27]:
ar.dtype

dtype('int32')

## int

In [33]:
ar.astype('int8') # 8bit
ar.astype('int16') # 16bit
ar.astype('int32') # 32bit
ar.astype('int64') # 64bit
# ar.astype('int128') Error

array([0, 1, 2, 3, 4], dtype=int64)

In [53]:
type(ar.astype('int64')[-1])

numpy.int64

## unsigned int

In [39]:
ar.astype('uint8')
ar.astype('uint16')
ar.astype('uint32')
ar.astype('uint64')
# ar.astype('uint128') Error

array([0, 1, 2, 3, 4], dtype=uint64)

## float

In [44]:
# ar.astype('float8') Error
ar.astype('float16')
ar.astype('float32')
ar.astype('float64') # default
# ar.astype('float128') Error

array([0., 1., 2., 3., 4.])

## str

In [48]:
ar_str = np.array(['hi'])
ar_str.dtype

dtype('<U2')

In [49]:
ar_str = np.array(['hello'])
ar_str.dtype

dtype('<U5')

In [50]:
ar_str = np.array(['오늘도 좋은 하루'])
ar_str.dtype

dtype('<U9')

In [51]:
ar_str = np.array(['hi', 'hello']) # 가장 긴 길이가 나옴
ar_str.dtype

dtype('<U5')

# 전치 행렬

In [54]:
ar2.shape

(2, 5)

In [55]:
ar2.transpose()

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [56]:
ar2.transpose().shape

(5, 2)

In [57]:
ar2.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
ar2.T.shape

(5, 2)

## 다차원 배열을 1차원 배열로 크기 변경(변형)

In [59]:
ar2.reshape(-1)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [60]:
ar2.flatten()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [61]:
ar2.ravel()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [62]:
ar3.reshape(-1)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4])

In [63]:
ar3.flatten()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4])

In [64]:
ar3.ravel()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4])